### ISSUE TITLE
ValueError: Secret signing key truncated 20 < 32

### ISSUE THREAD

**Issue by l-n-s** [MuxZeroNet/leaflet#2]
Trying to initiate a `leaflet.samtools.Dest` object from SAM reply throws an exception:

```

>>> leaflet.samtools.Dest(ddd, "base64", private=True, sig_type=7)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/lab/leaflet/leaflet/samtools.py", line 348, in __init__
    self.keys_cert = self.__class__.read_keys_cert(keyfile)
  File "/home/user/lab/leaflet/leaflet/samtools.py", line 406, in read_signing_secret_key
    secret_signing = cls._read(keyfile, key_len, throw='Secret signing key truncated')
  File "/home/user/lab/leaflet/leaflet/samtools.py", line 384, in _read
    raise ValueError(throw + ' %d < %d' % (len(data), read_len))
ValueError: Secret signing key truncated 20 < 32

```

Thou it says in [javadoc](http://docs.i2p2.de/javadoc/net/i2p/data/PrivateKeyFile.html) the following:

>Destination (387 bytes if no certificate, otherwise longer) - Public key (256 bytes) - Signing Public key (128 bytes) - Cert. type (1 byte) - Cert. length (2 bytes) - Certificate if length != 0 - Private key (256 bytes) - **Signing Private key (20 bytes)** Total 663 bytes

**Comment by l-n-s** [comment]
I need to investigate more. i2pd SAM creates DSA_SHA1 dest by default, which is 20 bytes.
